### ISSUE TITLE
graph_encoder method 

### ISSUE THREAD

**Issue by Tabatabaei1999** [JinyuZ1996/LEA-GCN#1]
hello, I read the paper but couldn't find that graph_encoder function expressed in which part of the paper.

**Comment by JinyuZ1996** [comment]
Dear Researcher, the function "graph_encoder" is correlated to the Eq.5 to Eq.7, it is a simplified LightGCN encoder, which was coverted to the cross-domain version and remove the multi-layer aggregation protocol. I hope the above answers can help you.

**Comment by Amirmohammad-Bamdad** [comment]
Hi @JinyuZ1996. In LEA_Model.py, in the graph_encoder function, on line 129, a loop is defined, and then in each iteration of it, additional information (a fold from unzipped information that is extracted from Laplacian) is added to the basic embedding of nodes. However, I could not find the concept of this matrix multiplication that adds auxiliary data to the basic embeddings in the paper. Could you please give a hint as to where is it located? 
Did I miss a concept provided in the LightGCN paper?

**Comment by JinyuZ1996** [comment]
> Hi @JinyuZ1996. In LEA_Model.py, in the graph_encoder function, on line 129, a loop is defined, and then in each iteration of it, additional information (a fold from unzipped information that is extracted from Laplacian) is added to the basic embedding of nodes. However, I could not find the concept of this matrix multiplication that adds auxiliary data to the basic embeddings in the paper. Could you please give a hint as to where is it located? Did I miss a concept provided in the LightGCN paper?

Please refer to the code provided by LightGCN at "https://github.com/kuandeng/LightGCN/blob/master/LightGCN.py", we just follow the seetings as LightGCN does (i.e., from line 236 to line 251 of "LightGCN.py").

**Comment by JinyuZ1996** [comment]
> Hi @JinyuZ1996. In LEA_Model.py, in the graph_encoder function, on line 129, a loop is defined, and then in each iteration of it, additional information (a fold from unzipped information that is extracted from Laplacian) is added to the basic embedding of nodes. However, I could not find the concept of this matrix multiplication that adds auxiliary data to the basic embeddings in the paper. Could you please give a hint as to where is it located? Did I miss a concept provided in the LightGCN paper?

The purpose of setting the self loop in LightGCN is to consider the feature information of nodes themselves during the graph convolution process, so that the model can also have excellent performance in cold start scenarios. I speculate that you may have been misled by the comment added on line 129 of LEA_Module.py. In fact, the operation here is no different from LightGCN, we only used a cross domain version to adapt it to cross domain sequence recommendation scenarios. At present, we have removed this potentially misleading comment. Thank you for your reading.

**Comment by Amirmohammad-Bamdad** [comment]
> > Hi @JinyuZ1996. In LEA_Model.py, in the graph_encoder function, on line 129, a loop is defined, and then in each iteration of it, additional information (a fold from unzipped information that is extracted from Laplacian) is added to the basic embedding of nodes. However, I could not find the concept of this matrix multiplication that adds auxiliary data to the basic embeddings in the paper. Could you please give a hint as to where is it located? Did I miss a concept provided in the LightGCN paper?
> 
> The purpose of setting the self loop in LightGCN is to consider the feature information of nodes themselves during the graph convolution process, so that the model can also have excellent performance in cold start scenarios. I speculate that you may have been misled by the comment added on line 129 of LEA_Module.py. In fact, the operation here is no different from LightGCN, we only used a cross domain version to adapt it to cross domain sequence recommendation scenarios. At present, we have removed this potentially misleading comment. Thank you for your reading.

Thank you so much for your response.
